### ISSUE TITLE
Thanks for your work and I'm really looking forward to the code.

### ISSUE THREAD

**Issue by ty5491003** [WSP-LAB/Montage#1]
Could you tell me when do you plan to upload the code? Thx. 😆

**Comment by leeswimming** [comment]
Thank you for your interest on our work. We will make the code public within 3 months.

**Comment by ty5491003** [comment]
I get it, thx.

**Comment by 1789120321** [comment]
Hello, I am very interested in your work, and hope to get the code and data of your project. When can you upload the code and data?

**Comment by leeswimming** [comment]
Thank you for your interest in our work. We have already released our data.
You can find it at https://github.com/WSP-LAB/js-test-suite.

We will release the code after the conference, which will be held on August 12–14, 2020.
