### ISSUE TITLE
fail to get chakracore

### ISSUE THREAD

**Issue by Anderson-Xia** [WSP-LAB/Montage#2]
Hello! You've mentioned "eng_path": "/home/user/ChakraCore/out/Release/ch" in config file. But I can't find such directory.  And I tried ChakraCore/bin/ch but it didn't work. So how can I download the engine as yours?

By the way, I'm looking forward to the code for phase 2 and 3.
Thank you for replying.

**Comment by leeswimming** [comment]
Thanks for your question! The path in the `config.json` file is just an example. You need to clone the [ChakraCore repository](https://github.com/Microsoft/ChakraCore/) and build ChakraCore before running Montage. This [link](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore) provides how you can build ChakraCore.

**Comment by Anderson-Xia** [comment]
Thx
