### ISSUE TITLE
When are you going to release the code for Phase II and Phase III?

### ISSUE THREAD

**Issue by QuXing9** [WSP-LAB/Montage#3]
First of all, congratulation on your work, it is amazing!

And I am very interested in the montage and would like to reproduce it on my computer, So I want to know when will the code for phase II and phase III be released? 

Thank you in advance!

**Comment by leeswimming** [comment]
We are currently inspecting the code. If there exist no problem, I will release the code next week. Thank you!

**Comment by QuXing9** [comment]
> We are currently inspecting the code. If there exist no problem, I will release the code next week. Thank you!

Got it, thx!
